version: "3.9"
services:
  docker:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    image: $DOCKER_REPO
    # aby se nemuselo neustale vystavovat znovu
    volumes:
      - ./:/code
      - ./data:/data
    mem_limit: 256m