version: "3.9"
services:
  docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: pavlamor/ex_demo
    # aby se nemuselo neustale vystavovat znovu
    volumes:
      - ./:/code
      - ./data:/data
    mem_limit: 256m